const SCREENS = {
    AUTH: 'AUTH_SCREEN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD_SCREEN',
    HOME: 'HOME_SCREEN',
    PROFILE: 'PROFILE_SCREEN',
    MY_PROFILE: 'MY_PROFILE_SCREEN',
    SETTING: 'SETTING_SCREEN',
};

export default SCREENS;