const SCREENS = {
  AUTH: 'AUTH_SCREEN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  HOME: 'MAIN_PAGE_SCREEN',
  BAG: 'MY_BAG_SCREEN',
  SHOP: 'CATEGORIES_SCREEN',
  FAVORITES: 'MY_FAVORITE_SCREEN',
  PROFILE: 'MY_PROFILE_SCREEN',
};

export default SCREENS;
